SELECT G.NOMBRE, COUNT(P.TICKETS_VENDIDOS) AS VENTAS FROM PELICULAS AS P
INNER JOIN GENEROS AS G ON  P.IDGENERO=G.IDGENERO
INNER JOIN ACTORES AS A ON P.IDPAIS=A.IDPAIS
GROUP BY G.NOMBRE
HAVING SUM(P.TICKETS_VENDIDOS)=10000
ORDER BY G.NOMBRE


SELECT P.NOMBRE, AVG(PE.PUNTAJE) AS PROMEDIO_PUNTAJE FROM PELICULAS AS PE
INNER JOIN PAISES AS P ON PE.IDPAIS = P.IDPAIS
GROUP BY P.NOMBRE
--HAVING AVG(PE.PUNTAJE) > 7.5